name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Checking out
      uses: actions/checkout@v1
    - name: Invoke MSBuild
      run: cibuild.bat
      shell: cmd
    - name: Uploading files
      uses: actions/upload-artifact@v1
      with:
        name: Release build
        path: bin/Release
